version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.5
        environment:
          MIX_ENV: ci

    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Download and compile
          command: |
            mix local.hex --force
            mix local.rebar --force
            mix deps.get
            mix compile
            mix eqc.install --mini --force

      - run:
          name: Running test
          command: mix test

      - store_test_results:
          path: ./_build/ci/lib/mathematics/